version: '3.9'

services:
  simsapi:
    build: .
    hostname: simsapi
    # command: gunicorn dnaorder.wsgi:application --bind 0.0.0.0:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app 
      - data_volume:/data
    environment:
      - VERSION=DOCKER
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    # env_file:
    #   - ./.env.dev
    networks:
      # - shared-network
      - sims-network
    ports:
      - "11111:11111"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - sims-network
  spa2:
    build:
        context: ./spa2
        dockerfile: dev.Dockerfile
    hostname: spa2
    ports:
      - "5050:5050"
    networks:
      - sims-network
    volumes:
      - ./spa2:/app
    depends_on:
      - simsapi
volumes:
  postgres_data:
  data_volume:
networks:
  sims-network:
  # shared-network: #for communicating with other docker application APIs used by plugins.  First run: docker network create shared-network
  #   external: true
