# Generated by Django 2.2.3 on 2019-07-16 19:14

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('adapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to='sims.Adapter')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_lanes', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('created', models.DateField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=25)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pi_first_name', models.CharField(max_length=50)),
                ('pi_last_name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=75)),
                ('type', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submission_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sample_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('submission_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sample_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('biocore', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sims.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('imported', models.DateTimeField(auto_now=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sims.Project')),
            ],
            options={
                'unique_together': {('name', 'project'), ('sample_id', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PoolPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooled_intermediate', to='sims.Pool')),
                ('pooled', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools_intermediate', to='sims.Pool')),
            ],
            options={
                'unique_together': {('pool', 'pooled')},
            },
        ),
        migrations.CreateModel(
            name='PoolLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sims.Library')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims.Pool')),
            ],
            options={
                'unique_together': {('pool', 'library')},
            },
        ),
        migrations.AddField(
            model_name='pool',
            name='libraries',
            field=models.ManyToManyField(related_name='pools', through='sims.PoolLibrary', to='sims.Library'),
        ),
        migrations.AddField(
            model_name='pool',
            name='pools',
            field=models.ManyToManyField(related_name='pooled', through='sims.PoolPool', to='sims.Pool'),
        ),
        migrations.AddField(
            model_name='library',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='sims.Sample'),
        ),
        migrations.CreateModel(
            name='RunPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sims.Pool')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='sims.Run')),
            ],
            options={
                'unique_together': {('run', 'index')},
            },
        ),
    ]
