# Generated by Django 2.2.3 on 2019-07-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='submission',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('name', 'project'), ('sample_id', 'project')},
        ),
    ]
