# Generated by Django 2.2.3 on 2019-07-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(db_index=True, default='samplename', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runpool',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_pools', to='sims.Run'),
        ),
    ]
