# Generated by Django 2.2.3 on 2019-07-12 23:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0002_auto_20190712_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
