# Generated by Django 2.2.3 on 2019-08-29 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0004_auto_20190725_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='runpool',
            options={'ordering': ['run', 'index']},
        ),
        migrations.RemoveField(
            model_name='adapter',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='adapter',
            name='description',
        ),
        migrations.AddField(
            model_name='adapter',
            name='barcodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='machine',
            name='num_lanes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
