# Generated by Django 2.2.3 on 2019-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0005_auto_20190829_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterdb',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
