# Generated by Django 2.2.3 on 2019-08-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_auto_20190829_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='db',
            field=models.ForeignKey(default='10x', on_delete=django.db.models.deletion.CASCADE, to='sims.AdapterDB'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='adapter',
            unique_together={('db', 'name')},
        ),
    ]
