# Generated by Django 2.2.3 on 2019-08-30 17:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_auto_20190829_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='barcode',
        ),
        migrations.AddField(
            model_name='library',
            name='barcodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
